<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "news_grouped_by_date"
 *
 * Auto generated by Extension Builder 2014-10-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'News grouped by Date',
	'description' => 'ViewHelper for grouping Newsitems by Date',
	'category' => 'plugin',
	'author' => 'Alexander Nikolas Reuber',
	'author_email' => 'info@unconnect.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'news' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);